Repository PJ-Plan-Journey/PJ-Plan-Journey-FE, pull requests merged in 2024-08, with the labels that each got.

#23 Feature/main page 20 : design & feature
  package-lock.json
  package.json
  src/axios/api.js
  src/components/Header/DropdownMenu.jsx
  src/components/Header/Header.jsx
  src/components/Header/NotificationMenu.jsx
  src/components/MyPage/AccountSettings.jsx
  src/components/MyPage/FriendManagement.jsx
  src/components/MyPage/MainContent.jsx
  src/components/MyPage/Menu.jsx
  src/components/MyPage/Modal.jsx
  src/components/MyPage/Sidebar.jsx
  src/components/MyPage/TravelManagement.jsx
  src/components/PlanShareBoard/PlanShareBoard.jsx
  src/components/common/Header.jsx
  src/components/index.jsx
  src/components/main/Carousel.jsx
  src/components/main/TravelRecommendations.jsx
  src/pages/LoginPage.jsx
  src/pages/MainPage.jsx
  src/pages/MyPage.jsx
  src/pages/PlanShareBoardPage.jsx
  src/pages/ProfilePage.jsx
  src/pages/SignupPage.jsx
  src/routers/Router.jsx
  src/styles/main/Header.styles.js
  src/styles/main/TravelRecommendations.style.js
  src/styles/mypage/AccountSettings.styles.jsx
  src/styles/mypage/FriendManagement.styles.jsx
  src/styles/mypage/MainContent.styles.jsx
  src/styles/mypage/MyPage.styles.jsx
  src/styles/mypage/Sidebar.styles.jsx
  src/styles/mypage/TravelManagement.styles.jsx
  src/styles/planShare/PlanShareBoard.styles.js
  src/zustands/friend/useFriendStore.js
  vite.config.js
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css

#24 Feature/plan board 21
  package.json
  src/components/plan/KakaoMap.jsx
  src/components/plan/place/PlaceListItem.jsx
  src/components/plan/place/SelectPlace.jsx
  src/components/plan/place/SelectedIPlace.jsx
  src/components/plan/place/SelectedList.jsx
  src/pages/PlanBoardsPage.jsx
  src/pages/PlanPage.jsx
  src/routers/Router.jsx
  src/styles/common/common.style.jsx
  src/styles/plan/KakaoMap.style.jsx
  src/styles/plan/Modal.style.jsx
  src/styles/plan/PlanPage.style.jsx
  src/styles/plan/date/CalendarModal.style.jsx
  src/styles/plan/date/SelectedDate.style.jsx
  src/styles/plan/place/PlaceListItem.style.jsx
  src/styles/plan/place/SelectPlace.style.jsx
  src/styles/plan/place/SelectedList.style.jsx
  src/zustands/plan/useDateStore.js
  src/zustands/plan/usePlaceStore.js
  yarn.lock
Labels: 🎨 Html&css, 🔨 Refactor

#29 feature : API연결_AccountSettings. FriendManagement 수정중.
  src/ProtectedRoute.jsx
  src/axios/api.js
  src/components/Header/DropdownMenu.jsx
  src/components/Header/Header.jsx
  src/components/MyPage/AccountSettings.jsx
  src/components/MyPage/FriendManagement.jsx
  src/components/MyPage/MainContent.jsx
  src/components/MyPage/Menu.jsx
  src/components/MyPage/TravelManagement.jsx
  src/components/ProtectedRoute.jsx
  src/components/auth/LoginForm.jsx
  src/components/auth/SignupForm.jsx
  src/pages/LoginPage.jsx
  src/pages/PlanBoardsPage.jsx
  src/pages/SignupPage.jsx
  src/routers/Router.jsx
  src/styles/auth/Signup.styles.jsx
  src/styles/main/Header.styles.js
  src/styles/main/TravelRecommendations.style.js
  src/styles/mypage/FriendManagement.styles.jsx
  src/styles/mypage/Sidebar.styles.jsx
  src/styles/mypage/TravelManagement.styles.jsx
  src/zustands/authStore.js
  src/zustands/bearStore.js
  src/zustands/useAuthStore.js
  vite.config.js
Labels: ✨ Feature, 🥰 Accessibility

#34 fix : token이 response header에 포함되도록함.
  src/components/auth/LoginForm.jsx
Labels: 📬 API

#35 Feature/mypage 26
  src/axios/api.js
  src/components/MyPage/FriendManagement.jsx
  src/components/MyPage/TravelManagement.jsx
  src/components/plan/TitleForm.jsx
  src/styles/mypage/TravelManagement.styles.jsx
Labels: 📬 API, 🎨 Html&css

#36 Feature/creat plan api 33
  package.json
  src/axios/api.js
  src/components/plan/TitleForm.jsx
  src/components/plan/board/BoradList.jsx
  src/components/plan/board/detail/DayList.jsx
  src/pages/PlanDetailPage.jsx
  src/pages/PlanPage.jsx
  src/routers/Router.jsx
  src/zustands/plan/useStepStore.js
  vite.config.js
  yarn.lock
Labels: ✨ Feature, 📬 API, 🎨 Html&css

#37 fix : API. 친구 삭제 기능 미구현
  public/index.html
  src/assets/kakao_login_medium_wide.png
  src/axios/api.js
  src/components/Header/DropdownMenu.jsx
  src/components/Header/Header.jsx
  src/components/MyPage/AccountSettings.jsx
  src/components/MyPage/FriendManagement.jsx
  src/components/MyPage/MainContent.jsx
  src/components/MyPage/ShareButton.jsx
  src/components/MyPage/TravelManagement.jsx
  src/components/auth/LoginForm.jsx
  src/styles/main/Header.styles.js
  src/styles/mypage/FriendManagement.styles.jsx
  src/styles/mypage/TravelManagement.styles.jsx
  src/types.d.ts
Labels: 📬 API

#42 Feature/websocket 41
  src/components/auth/LoginForm.jsx
  src/components/plan/board/detail/DayList.jsx
  src/components/plan/board/detail/PlanListTitle.jsx
  src/components/plan/board/detail/buttonGruop/FriendButton.jsx
  src/pages/PlanBoardsPage.jsx
Labels: 📬 API

#46 fix : 친구관리 API, feature : 게시판
  src/axios/api.js
  src/components/Header/Header.jsx
  src/components/MyPage/FriendManagement.jsx
  src/components/MyPage/TravelManagement.jsx
  src/components/ShareBoard.jsx
  src/components/plan/board/BoardList.jsx
  src/pages/PlanBoardsPage.jsx
  src/pages/ShareBoardsPage.jsx
  src/routers/Router.jsx
  src/styles/main/Header.styles.js
  src/styles/mypage/FriendManagement.styles.jsx
  src/styles/mypage/MainContent.styles.jsx
  src/styles/shareboard/ShareBoard.styles.js
Labels: ✨ Feature, 📬 API, 🎨 Html&css

#49 fix : FriendManagement infinite scroll
  package.json
  src/components/MyPage/FriendManagement.jsx
  src/styles/mypage/FriendManagement.styles.jsx
  yarn.lock
Labels: ✨ Feature

#51 feature : ShareBoard API 연결
  src/assets/150x150.png
  src/components/Header/Header.jsx
  src/components/MyPage/FriendManagement.jsx
  src/components/MyPage/ShareButton.jsx
  src/components/MyPage/TravelManagement.jsx
  src/components/ShareBoard.jsx
  src/pages/ShareBoardsPage.jsx
  src/styles/shareboard/ShareBoard.styles.js
Labels: ✨ Feature, 📬 API, 🎨 Html&css

#52 feature : 댓글&대댓글 페이지네이션
  src/components/plan/board/detail/Comment.jsx
  src/components/plan/board/detail/CommentList.jsx
  src/components/plan/board/detail/Reply.jsx
  src/components/plan/board/detail/ReplyItem.jsx
  src/styles/plan/board/detail/Comment.style.jsx
  src/styles/plan/board/detail/CommentList.style.jsx
  src/styles/plan/board/detail/Reply.style.jsx
  src/styles/plan/board/detail/ReplyItem.style.jsx
Labels: ✨ Feature, 🎨 Html&css

#54 Design/plan detail 53
  src/axios/api.js
  src/components/Header/Header.jsx
  src/components/Header/NotificationMenu.jsx
  src/components/MyPage/ShareButton.jsx
  src/components/plan/board/detail/DayList.jsx
  src/components/plan/board/detail/buttonGruop/FriendButton.jsx
  src/pages/PlanBoardsPage.jsx
  src/styles/main/Header.styles.js
  src/styles/plan/board/detail/DayList.style.jsx
Labels: ✨ Feature, 📬 API, 🎨 Html&css

#55 Feature/share board 50
  src/components/MyPage/FriendManagement.jsx
  src/components/MyPage/ShareButton.jsx
  src/components/ShareBoard.jsx
  src/pages/ShareBoardsPage.jsx
  src/styles/mypage/FriendManagement.styles.jsx
  src/styles/mypage/TravelManagement.styles.jsx
Labels: ✨ Feature, 📬 API, 🎨 Html&css, 🥰 Accessibility
